Description:  Un Cloud Formation que crea 
  Un Grupo Racer org Admin
  Un Usuario Racer Admin
  Name racer-gropus-stack


Parameters:
    
  MyLabName:
    Description: Lab Name
    Type: String
    Default: Racer Lab

Resources:
  
  RacerGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: Racer-Admin
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess


  RacerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: Racer
      LoginProfile: 
        Password: CambiameLaPas!!
        PasswordResetRequired: true
      Groups: 
        - !Ref RacerGroup
      Path: /racer/


Outputs:

  RacerGroup:
    Description: Grupo RacerGroup
    Value: !Ref RacerGroup

  RacerUser:
    Description: User RacerUser
    Value: !Ref RacerUser



