Description:  Un Cloud Formation que crea 
  Un Grupo Admin
  Un Usuario Racer 
  Un Rol DeepRacer


Parameters:
    
  MyLabName:
    Description: Lab Name
    Type: String
    Default: Deep Racer Lab

Resources:
  
  DRCloudGroup:
    Type: "AWS::IAM::Group"
    Properties:
      GroupName: DR-Cloud-Admin
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
        - arn:aws:iam::aws:policy/AWSBillingReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSBudgetsActionsWithAWSResourceControlAccess


  RacerUser:
    Type: AWS::IAM::User
    Properties:
      UserName: racer1
      LoginProfile: 
        Password: CambiameLaPas!!
        PasswordResetRequired: true
      Groups: 
        - !Ref DRCloudGroup
      Path: /racers/


  DeepRacerCloudRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      RoleName: DeepRacerCloudRole 
      Description: IAM role for EC2 instance en DRFC
      ManagedPolicyArns: 
        - arn:aws:iam::aws:policy/AmazonKinesisVideoStreamsFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccessV2
      AssumeRolePolicyDocument: # (required) only one trust policy with a role
        Version: '2012-10-17'
        Statement: 
          - 
            Effect: Allow
            Principal: 
              Service: 
                - 'ec2.amazonaws.com'
            Action: 
              - 'sts:AssumeRole'
 #    MaxSessionDuration: 3600 # in seconds, 1 hour
      Path: '/racers/'

  
  DeepRacerCloudProfile: 
    Type: 'AWS::IAM::InstanceProfile'
    Properties: 
      InstanceProfileName: DeepRacerCloudProfile
      Roles: 
        - !Ref DeepRacerCloudRole
      Path: '/racers/'



Outputs:

  DRCloudGroup:
    Description: Grupo DRCloudGroup
    Value: !Ref DRCloudGroup

  RacerUser:
    Description: User RacerUser
    Value: !Ref RacerUser

  DeepRacerCloudRole:
    Description: Role DeepRacerCloudRole
    Value: !Ref DeepRacerCloudRole


