Description:  Un Cloud Formation que crea los Buckets
  Esta en WIP
  Los Buckets deseados son
  El de las ssh
  Etc ...
  Como lo hago privado y me quedo tranquilo?
  Name dr-cloud-s3-stack


Parameters:
    
  MyLabName:
    Description: Lab Name
    Type: String
    Default: Deep Racer Lab

Resources:
  
  DrConfigBucket: 
    Type: 'AWS::S3::Bucket' 
    Properties:
      BucketName: dr-racer3-sao-config
      Tags:
        - Key: lab
          Value: DeepRacer

  DrModelsBucket: 
    Type: 'AWS::S3::Bucket' 
    Properties:
      BucketName: dr-racer3-sao-models-to-pabloedu-gmail
      Tags:
        - Key: lab
          Value: DeepRacer
  

Outputs:
 
  DrConfigBucket:
    Description: Racer Bucket
    Value: !Ref DrConfigBucket

  DrModelsBucket:
    Description: Racer Bucket
    Value: !Ref DrModelsBucket


